version: '3'
services:
  postgres:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRESS_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - c:/data:/var/lib/postgresql/data