version: '3'
services:
  admin:
    build: ./admin
    ports:
      - "3000:80"
    links:
      - server:server
  server: 
    build: ./server
    links: 
      - postgres:postgres
    ports:
      - "8080:8080"
  postgres:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRESS_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data